#!/usr/bin/env node
/**
 * Load the session logs written to disk into the sessions table.
 *
 *   node scripts/migrate-logs.js | psql "$SUPABASE_DB_URL"
 *
 * The main migration moves the prompt list, accounts and contributions. Logs
 * are separate because they were written as files per sitting, before there
 * was a table to put them in, and some of them refer to word sets that no
 * longer exist — the hand-written packs that preceded the tracker sheet.
 *
 * A log naming a category that is not in the database keeps its run sheet and
 * loses only the category link, rather than being dropped: what happened in
 * that sitting is still a record of the archive being built.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const datasetDir = process.env.SOLARIS_DATASET_DIR || path.join(root, 'dataset');
const known = new Set(
  JSON.parse(fs.readFileSync(path.join(root, 'data', 'words.json'), 'utf8'))
    .categories.map(c => c.id));

function lit(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

const rows = [];
let orphanedCategory = 0;

const contributorsDir = path.join(datasetDir, 'contributors');
if (fs.existsSync(contributorsDir)) {
  for (const who of fs.readdirSync(contributorsDir)) {
    const logDir = path.join(contributorsDir, who, 'logs');
    if (!fs.existsSync(logDir)) continue;

    for (const file of fs.readdirSync(logDir).filter(f => f.endsWith('.json'))) {
      let log;
      try { log = JSON.parse(fs.readFileSync(path.join(logDir, file), 'utf8')); }
      catch { continue; }

      const category = log.pack && log.pack.id;
      const linkable = category && known.has(category);
      if (category && !linkable) orphanedCategory++;

      rows.push({
        contributor: log.contributor || log.speaker || who,
        category: linkable ? category : null,
        started_at: log.startedAt || log.finishedAt,
        finished_at: log.finishedAt || log.startedAt,
        // Logs written before quitting and finishing were told apart do not
        // say which they were; they are recorded as completed rather than
        // guessed at.
        ended_how: log.endedHow === 'quit' ? 'quit' : 'completed',
        xp: log.xp || 0,
        recorded: (log.totals && log.totals.recorded) || 0,
        skipped: (log.totals && log.totals.skipped) || 0,
        detail: log.items || null,
      });
    }
  }
}

if (!rows.length) {
  console.error('  no session logs found on disk');
  process.exit(0);
}

// Only logs belonging to an account that exists — the foreign key would
// reject the rest and take the transaction with them.
const cols = Object.keys(rows[0]);
let sql = '-- Generated by scripts/migrate-logs.js\nbegin;\n\n';
for (const row of rows) {
  sql += `insert into sessions (${cols.join(', ')})\n` +
         `select ${cols.map(c => lit(row[c])).join(', ')}\n` +
         `where exists (select 1 from contributors where username = ${lit(row.contributor)});\n`;
}
sql += '\ncommit;\n';

console.error(`  session logs:  ${rows.length}`);
if (orphanedCategory) {
  console.error(`  ${orphanedCategory} refer to a word set that no longer exists — kept, category left null`);
}
process.stdout.write(sql);
