#!/usr/bin/env node
/**
 * Emit the migration as SQL, for loading over a direct Postgres connection.
 *
 *   node scripts/migrate-sql.js | psql "$SUPABASE_DB_URL"
 *
 * The other migration path (scripts/migrate-to-supabase.js) goes through
 * PostgREST and needs a service key. This one needs only the database
 * connection string, which is what you already have if you can apply the
 * schema at all.
 *
 * Both build their rows from the same functions in db.js, so the two paths
 * cannot drift apart.
 *
 * Every statement upserts on its primary key: running this twice updates
 * rather than duplicating, and a half-finished run can simply be repeated.
 */
const fs = require('fs');
const path = require('path');
const { FileDb, buildSeedRows, buildAccountRows } = require('../db.js');

const root = path.join(__dirname, '..');

function lit(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

/** One multi-row INSERT per chunk, with an upsert on conflict. */
function insertAll(table, rows, conflict, update, chunk = 400) {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]);
  const setter = update.map(c => `${c} = excluded.${c}`).join(', ');
  let sql = '';

  for (let i = 0; i < rows.length; i += chunk) {
    const values = rows.slice(i, i + chunk)
      .map(r => `  (${cols.map(c => lit(r[c])).join(', ')})`)
      .join(',\n');
    sql += `insert into ${table} (${cols.join(', ')}) values\n${values}\n` +
           `on conflict (${conflict}) do update set ${setter};\n\n`;
  }
  return sql;
}

const out = [];
out.push('-- Generated by scripts/migrate-sql.js. Safe to re-run.\nbegin;\n');

// ── Reference data ────────────────────────────────────────────────────────────
const wordsDoc = JSON.parse(fs.readFileSync(path.join(root, 'data', 'words.json'), 'utf8'));
const seed = buildSeedRows(wordsDoc);

out.push(insertAll('categories', seed.categories, 'id',
  ['name', 'icon', 'accent', 'description', 'sort_order']));
out.push(insertAll('words', seed.words, 'id',
  ['category', 'te', 'translit', 'en', 'level', 'word_order', 'active']));

// ── Anything recorded while the server was running on files ──────────────────
const usersFile = process.env.SOLARIS_USERS_FILE || path.join(root, '.solaris-users.json');
const indexFile = process.env.SOLARIS_WORD_INDEX || path.join(root, '.solaris-words.json');

if (fs.existsSync(usersFile)) {
  const local = new FileDb({
    wordsFile: path.join(root, 'data', 'words.json'),
    usersFile,
    indexFile,
  });

  const accounts = buildAccountRows(local._users.users, local._index);

  out.push(insertAll('contributors', accounts.contributors, 'username',
    ['display_name', 'password_hash', 'password_salt', 'xp', 'words_count',
     'streak', 'best_streak', 'last_login_at']));

  // Only contributions whose word is actually in the list being seeded; a
  // recording of a prompt that no longer exists would fail the foreign key and
  // take the whole transaction with it.
  const known = new Set(seed.words.map(w => w.id));
  const usable = accounts.contributions.filter(c => known.has(c.word_id));
  const dropped = accounts.contributions.length - usable.length;

  out.push(insertAll('contributions', usable, 'contributor,word_id', ['outcome', 'created_at']));

  // The signing secret comes across, or every token issued so far stops working
  // and everyone is signed out by the move.
  if (local._users.secret) {
    out.push(`insert into app_secrets (key, value) values ('token_secret', ${lit(local._users.secret)})\n` +
             `on conflict (key) do update set value = excluded.value;\n\n`);
  }

  console.error(`  accounts:      ${accounts.contributors.length}`);
  console.error(`  contributions: ${usable.length}${dropped ? ` (${dropped} skipped — unknown word id)` : ''}`);
} else {
  console.error('  no local accounts to carry over');
}

out.push('commit;\n');
console.error(`  categories:    ${seed.categories.length}`);
console.error(`  words:         ${seed.words.length}`);

process.stdout.write(out.join(''));
